services:
  # Backend API service
  - type: web
    name: boxwise-api
    env: node
    buildCommand: cd server && npm install express-fileupload && npm install && cd ../scripts && npm install
    startCommand: cd scripts && node check-and-init-db.js && cd ../server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGO_URI
        sync: false # This will be set manually in the Render dashboard
      - key: JWT_SECRET
        sync: false # This will be set manually in the Render dashboard
      - key: JWT_EXPIRE
        value: 30d
      - key: ASSET_ID_AUTO_INCREMENT
        value: "true"
      - key: ASSET_ID_PREFIX
        value: "000-"
      - key: MAX_FILE_SIZE
        value: "5000000"
      - key: UPC_API_URL
        value: https://api.upcitemdb.com/prod/trial/lookup
      - key: CUSTOM_FIELDS_ENABLED
        value: "true"
      - key: CUSTOM_FIELD_TYPES
        value: "text,integer,boolean,timestamp"
      - key: CUSTOM_FIELDS_URL_MARKDOWN
        value: "true"
      - key: CUSTOM_FIELDS_FEATURES
        value: "url_markdown,url_detection,email_detection"

  # Frontend static site
  - type: web
    name: boxwise-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://boxwise-api-hc0t.onrender.com/*
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production

# Note: To create the owner user, run the following command in the Render.com shell:
# cd scripts && npm install jsonwebtoken && node create-owner-render.js terry@jknelotions.com "cde3CDE#vfr4VFR$" "Terry"
