services:
  # Backend API service
  - type: web
    name: boxwise-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGO_URI
        sync: false # This will be set manually in the Render dashboard
      - key: JWT_SECRET
        sync: false # This will be set manually in the Render dashboard
      - key: UPC_API_URL
        value: https://api.upcitemdb.com/prod/trial/lookup

  # Frontend static site
  - type: web
    name: boxwise-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://boxwise-api.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
